/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.artiste.sudoku;

import org.artiste.sudoku.generator.Generator;
import org.artiste.sudoku.generator.SmartGenerator;

public class App {

  public static void main(String[] args) {
    Generator generator = new SmartGenerator();
  }
}
