/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.artiste.sudoku;

import org.artiste.sudoku.model.Sudoku;

public class App {

  public static void main(String[] args) {
    Sudoku sudoku = new Sudoku();
    System.out.print(sudoku);
  }
}
